---
{{- $peeringRequest := (merge (dict "name" "peering-request" "module" "discovery") .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liqo.prefixedName" $peeringRequest }}
  labels:
    {{- include "liqo.labels" $peeringRequest | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "liqo.selectorLabels" $peeringRequest | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "liqo.labels" $peeringRequest | nindent 8 }}
      {{- if .Values.peeringRequest.pod.labels }}
        {{- toYaml .Values.peeringRequest.pod.labels | nindent 8 }}
      {{- end }}
      {{- if .Values.peeringRequest.pod.annotations }}
      annotations:
        {{- toYaml .Values.peeringRequest.pod.annotations | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "liqo.prefixedName" $peeringRequest }}
      containers:
        - image: {{ .Values.peeringRequest.imageName }}{{ include "liqo.suffix" $peeringRequest }}:{{ include "liqo.version" $peeringRequest }}
          name: {{ $peeringRequest.name }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          ports:
            - containerPort: 8443
          args:
            - "--broadcaster-image"
            - {{ .Values.advertisement.broadcasterImageName }}{{ include "liqo.suffix" $peeringRequest }}:{{ include "liqo.version" $peeringRequest }}
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- if .Values.apiServer.address }}
            - name: APISERVER
              value: "{{ .Values.apiServer.address }}"
            {{- end }}
            {{- if .Values.apiServer.port }}
            - name: APISERVER_PORT
              value: "{{ .Values.apiServer.port }}"
            {{- end }}
            {{- if .Values.auth.ingress.host}}
            - name: AUTH_ADDR
              value: "{{ .Values.auth.ingress.host }}"
            {{- end }}
            {{- if .Values.auth.portOverride }}
            - name: AUTH_SVC_PORT
              value: "{{ .Values.auth.portOverride }}"
            {{- else if .Values.auth.ingress.enable }}
            - name: AUTH_SVC_PORT
              value: "443"
            {{- end }}
          resources:
            limits:
              cpu: 150m
              memory: 50M
            requests:
              cpu: 150m
              memory: 50M